### ISSUE TITLE
Error in Dashboard generation

### ISSUE THREAD

**Issue by kvosper** [HotelsDotCom/styx#160]
## The problem
An exception is thrown when trying to generate downstream.origins.origin[<some number>].requests.latency.mean

This exception only occurs very rarely and may be the result of a race condition.

```
java.lang.ArrayIndexOutOfBoundsException: null
	at org.HdrHistogram.AbstractHistogramIterator.next(AbstractHistogramIterator.java:100) ~[HdrHistogram-2.1.4.jar:2.1.4]
	at org.HdrHistogram.RecordedValuesIterator.next(RecordedValuesIterator.java:18) ~[HdrHistogram-2.1.4.jar:2.1.4]
	at org.HdrHistogram.AbstractHistogram.getMean(AbstractHistogram.java:1121) ~[HdrHistogram-2.1.4.jar:2.1.4]
	at org.HdrHistogram.AbstractHistogram.getStdDeviation(AbstractHistogram.java:1134) ~[HdrHistogram-2.1.4.jar:2.1.4]
	at com.hotels.styx.api.metrics.codahale.SlidingWindowHistogramReservoir$HistogramSnapshot.getStdDev(SlidingWindowHistogramReservoir.java:139) ~[styx-api-0.7-916.jar:na]
	at com.hotels.styx.metrics.reporting.graphite.GraphiteReporter.reportTimer(GraphiteReporter.java:308) [styx-proxy-0.7-916.jar:na]
	at com.hotels.styx.metrics.reporting.graphite.GraphiteReporter.doReport(GraphiteReporter.java:252) [styx-proxy-0.7-916.jar:na]
	at com.hotels.styx.metrics.reporting.graphite.GraphiteReporter.lambda$report$4(GraphiteReporter.java:236) [styx-proxy-0.7-916.jar:na]
	at java.util.TreeMap.forEach(TreeMap.java:1001) ~[na:1.8.0_60]
	at java.util.Collections$UnmodifiableMap.forEach(Collections.java:1505) ~[na:1.8.0_60]
	at com.hotels.styx.metrics.reporting.graphite.GraphiteReporter.report(GraphiteReporter.java:235) [styx-proxy-0.7-916.jar:na]
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:243) ~[metrics-core-3.2.6.jar:3.2.6]
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:182) ~[metrics-core-3.2.6.jar:3.2.6]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_60]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[na:1.8.0_60]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_60]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[na:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_60]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_60]
```

## Detailed description
This appears to be a thread-safety issue. Calling the snapshot.getMean() from multiple threads repeatedly causes the exception to be thrown.

See: https://github.com/HdrHistogram/HdrHistogram/blob/master/src/main/java/org/HdrHistogram/AbstractHistogramIterator.java#L103

The impact of this error appears to be relatively small as it will only prevent a single dashboard update.

## Acceptance criteria
* This exception should no longer occur

**Comment by mikkokar** [comment]
The dashboard is going to be deprecated due to new routing object model. Therefore won't do.
